export { compare as compareCustomisations } from './customisations/compare';
export { defaults as defaultCustomisations, mergeCustomisations, } from './customisations/index';
export { toBoolean } from './customisations/bool';
export { flipFromString, alignmentFromString, } from './customisations/shorthand';
export { rotateFromString } from './customisations/rotate';
export { stringToIcon, validateIcon as validateIconName } from './icon/name';
export { matchName as matchIconName } from './icon/index';
export { mergeIconData } from './icon/merge';
export { iconDefaults as defaultIconData, fullIcon as fullIconData, } from './icon/index';
export { parseIconSet, isVariation } from './icon-set/parse';
export { validateIconSet } from './icon-set/validate';
export { expandIconSet } from './icon-set/expand';
export { minifyIconSet } from './icon-set/minify';
export { getIcons } from './icon-set/get-icons';
export { getIconData } from './icon-set/get-icon';
export { convertIconSetInfo } from './icon-set/convert-info';
export { iconToSVG } from './svg/build';
export { replaceIDs } from './svg/id';
export { calculateSize } from './svg/size';
export { colorKeywords } from './colors/keywords';
export { stringToColor, compareColors, colorToString } from './colors/index';
export type { CustomIconLoader, CustomCollections, IconCustomizer, IconCustomizations, InlineCollection, } from './loader/types';
export { tryInstallPkg, mergeIconProps } from './loader/utils';
export { FileSystemIconLoader } from './loader/loaders';
export { getCustomIcon } from './loader/custom';
export { loadCollection, searchForIcon } from './loader/modern';
export { camelize, camelToKebab, pascalize } from './misc/strings';
